# Generated by Django 5.2.7 on 2025-10-21 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField(blank=True, help_text='Enter a SavedSearch name or raw search text.', null=True)),
                ('visualization_type', models.CharField(choices=[('table', 'Table'), ('chart', 'Chart')], default='table', max_length=16)),
                ('chart_type', models.CharField(blank=True, max_length=32, null=True)),
                ('x_field', models.CharField(blank=True, max_length=128, null=True)),
                ('y_field', models.CharField(blank=True, max_length=128, null=True)),
                ('by_field', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='dashboarding.dashboard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
