# Generated by Django 5.2.7 on 2025-10-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
