# Generated by Django 6.0.7 on 2026-09-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarding', '0002_dashboard_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='shared',
            field=models.BooleanField(default=False, help_text='Let every signed-in user view this dashboard. Editing and deleting stay with the owner.'),
        ),
    ]
