# Generated by Django 6.1.1 on 2026-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarding', '0003_dashboard_shared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['row', 'column', 'id']},
        ),
        migrations.AddField(
            model_name='panel',
            name='column',
            field=models.PositiveIntegerField(default=1, help_text="Left-to-right position within its row (1-indexed). Only ordering within the row matters — values don't need to be contiguous."),
        ),
        migrations.AddField(
            model_name='panel',
            name='row',
            field=models.PositiveIntegerField(default=1, help_text='Which row this panel appears in (1-indexed).'),
        ),
    ]
