# Generated by Django 5.2.6 on 2025-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.CharField(default='default', max_length=255)),
                ('sourcetype', models.CharField(default='default', max_length=255)),
                ('source', models.CharField(default='default', max_length=255)),
                ('host', models.CharField(default='default', max_length=255)),
                ('data', models.TextField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('extracted_fields', models.JSONField(default=dict)),
            ],
        ),
    ]
