# Generated by Django 5.2.6 on 2025-09-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.TextField(),
        ),
    ]
