# Generated by Django 5.2.6 on 2025-09-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='extracted_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
