# Generated by Django 5.2.7 on 2025-10-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_extracted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='index',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='sourcetype',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
    ]
