"""
Django settings for SIEMatic project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util
import os
import json
from pathlib import Path
import socket
import platform
import sys
import threading
from django.core.exceptions import ImproperlyConfigured
from events.extractors import is_json_sourcetype, extract_json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)
SECRET_KEY_PLACEHOLDER = 'replace-me-with-a-generated-secret-key'


def env_bool(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default):
    value = os.getenv(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY or SECRET_KEY == SECRET_KEY_PLACEHOLDER:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set to a generated secret key. '
        'Generate one with: '
        'python -c "from django.core.management.utils import get_random_secret_key; '
        'print(get_random_secret_key())"'
    )

DEBUG = env_bool('DJANGO_DEBUG', False)
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', ['localhost', '127.0.0.1', '::1'])

INTERNAL_IPS = [
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'drf_spectacular',
    'django_filters',
    'channels',
    'project',
    'events',
    'indexer',
    'agent',
    'search2',
    'dashboarding',
    'crawlers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
]

if DEBUG and os.getenv("INDEXER_MODE") != "1" and importlib.util.find_spec('debug_toolbar'):
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'SIEMatic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'SIEMatic.context_processors.indexer_mode',
            ],
        },
    },
]

WSGI_APPLICATION = 'SIEMatic.wsgi.application'

ASGI_APPLICATION = 'SIEMatic.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DATABASE_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DATABASE_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DATABASE_USER', ''),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
        'HOST': os.getenv('DATABASE_HOST', ''),
        'PORT': os.getenv('DATABASE_PORT', ''),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise static file storage (Django 4.2+ settings format).
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'project.CustomUser'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

TLS_ENABLED = env_bool('SIEMATIC_TLS_ENABLED', False)
SESSION_COOKIE_SECURE = TLS_ENABLED
CSRF_COOKIE_SECURE = TLS_ENABLED
SECURE_SSL_REDIRECT = TLS_ENABLED
SECURE_HSTS_SECONDS = 31536000 if TLS_ENABLED else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = TLS_ENABLED
SECURE_HSTS_PRELOAD = TLS_ENABLED

# Agent-to-indexer transport security.  This is separate from TLS_ENABLED
# because agents may connect to an indexer deployed on another host.
INDEXER_TLS = env_bool('INDEXER_TLS', TLS_ENABLED)
INDEXER_CA_BUNDLE = os.getenv('INDEXER_CA_BUNDLE') or None

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.filebased.EmailBackend')
EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured(
        'EMAIL_USE_TLS and EMAIL_USE_SSL are mutually exclusive; set only one.'
    )
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'siematic@example.com')
INGEST_THROTTLE_RATE = os.getenv('SIEMATIC_INGEST_THROTTLE_RATE', '20000/hour')
SEARCH_THROTTLE_RATE = os.getenv('SIEMATIC_SEARCH_THROTTLE_RATE', '120/min')
ANON_THROTTLE_RATE = os.getenv('SIEMATIC_ANON_THROTTLE_RATE', '20/hour')

LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {module} {process} {thread} {threadName} {pathname}:{lineno} {funcName} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'simple',
        },
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / f'{sys.argv[1] if len(sys.argv) > 1 and not sys.argv[1].startswith("-") else sys.argv[0]}.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.template': {
            'handlers': [],
            'level': 'INFO',
            'propagate': False,
        }
    },
}

# Log level from environment variable
LOGGING['root']['level'] = os.getenv('DJANGO_LOG_LEVEL', 'DEBUG' if DEBUG else 'WARNING').upper()
LOGGING['loggers']['django']['level'] = os.getenv('DJANGO_LOG_LEVEL', 'DEBUG' if DEBUG else 'WARNING').upper()

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'ingest': INGEST_THROTTLE_RATE,
        'search': SEARCH_THROTTLE_RATE,
        'anon': ANON_THROTTLE_RATE,
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'SIEMatic REST API',
    'DESCRIPTION': 'REST endpoints for event ingestion and saved searches.',
    'VERSION': '1.0.0',
}


FIELD_EXTRACTIONS = {
    is_json_sourcetype: extract_json,
}

SIEMATIC_SEARCH = {
    "COMMANDS": [
        "search2.commands.search:SearchCmd",
        "search2.commands.groupby:GroupByCmd",
        "search2.commands.annotate:AnnotateCmd",
        "search2.commands.to_dataframe:ToDataFrameCmd",
        "search2.commands.explode:ExplodeCmd",
        "search2.commands.drop:DropCmd",
        "search2.commands.run_saved_search:RunSavedSearchCommand",
        "search2.commands.filter:FilterCmd",
        "search2.commands.sort:SortCmd",
        "search2.commands.head:HeadCmd",
        "search2.commands.tail:TailCmd",
        "search2.commands.unique:UniqueCmd",
        "search2.commands.rename:RenameCmd",
        "search2.commands.stats:StatsCmd",
        "search2.commands.join:JoinCmd",
    ],
    "MAX_ROWS": 10_000,
    "ALLOWED_LOOKUPS": {
        "exact","iexact","contains","icontains","startswith","istartswith",
        "endswith","iendswith","in","gt","gte","lt","lte","range"
    },
    "AUTHZ_CHECK": "search2.engine.authz.default_check",
}
