# Generated by Django 6.0.7 on 2026-07-29 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_searches', to=settings.AUTH_USER_MODEL),
        ),
    ]
