from django.db import models
from events.models import Event

class Finding(models.Model):
    """
    Model to store findings generated by crawlers.
    """
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='findings')
    rule_name = models.CharField(max_length=255)
    description = models.TextField()
    severity = models.CharField(max_length=50, choices=[
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    ], default='medium')
    mitre_tactic = models.CharField(max_length=255, blank=True, null=True)
    mitre_technique = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.rule_name}: {self.description[:50]}"

    @classmethod
    def can_create_finding(cls, event, rule_name, cooldown_seconds=None):
        """
        Check if a finding can be created for the given event and rule within the cooldown period.
        Returns True if no recent finding exists, False otherwise.
        """
        if cooldown_seconds is None:
            return True
        from django.utils import timezone
        from datetime import timedelta
        cooldown_since = timezone.now() - timedelta(seconds=cooldown_seconds)
        return not cls.objects.filter(
            event=event,
            rule_name=rule_name,
            created_at__gte=cooldown_since
        ).exists()

    class Meta:
        ordering = ['-created_at']
