from django.db import models
from events.models import Event

class Finding(models.Model):
    """
    Model to store findings generated by crawlers.
    """
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='findings')
    rule_name = models.CharField(max_length=255)
    description = models.TextField()
    severity = models.CharField(max_length=50, choices=[
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('critical', 'Critical'),
    ], default='medium')
    mitre_tactic = models.CharField(max_length=255, blank=True, null=True)
    mitre_technique = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.rule_name}: {self.description[:50]}"

    class Meta:
        ordering = ['-created_at']
