# Generated by Django 6.1.1 on 2026-09-07 19:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=255, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('address', models.GenericIPAddressField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('events_delivered', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siematic_agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=512)),
                ('batch_id', models.CharField(max_length=255)),
                ('content_digest', models.CharField(max_length=64)),
                ('cursor', models.TextField()),
                ('count', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'batch_id'), name='agent_receipt_target_batch_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=512, unique=True)),
                ('cursor', models.TextField()),
                ('index', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=512)),
                ('events_delivered', models.PositiveBigIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='agent.agent')),
            ],
        ),
    ]
