# Generated by Django 6.0.3 on 2026-03-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_userprofile_theme_preference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_event', 'Can view events'), ('view_dashboard', 'Can view dashboards'), ('view_panel', 'Can view panels'), ('view_finding', 'Can view findings'), ('view_savedsearch', 'Can view SavedSearches')]},
        ),
    ]
