# Generated by Django 6.0.7 on 2026-07-29 12:16

from django.db import migrations

ORPHANED_PERMISSION_CODENAMES = [
    "view_event",
    "view_dashboard",
    "view_panel",
    "view_finding",
    "view_savedsearch",
]


def delete_orphaned_project_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")

    Permission.objects.filter(
        content_type__app_label="project",
        content_type__model="customuser",
        codename__in=ORPHANED_PERMISSION_CODENAMES,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_customuser_options'),
        ('events', '0004_alter_event_host_alter_event_index_and_more'),
        ('dashboarding', '0002_dashboard_defaults'),
        ('crawlers', '0001_initial'),
        ('search2', '0002_savedsearch_is_public_savedsearch_shared_with'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RunPython(delete_orphaned_project_permissions, migrations.RunPython.noop),
    ]
